# Generated by Django 4.1.3 on 2022-11-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_book_url_book_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='kind',
        ),
    ]
